### PR TITLE
Remove the duplication of Attributes table in documentation of enums

### PR DESCRIPTION
**Pull request by OrkoHunter**
http://orkohunter-networkx-metis.readthedocs.org/en/test

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Are we not interested in this?
I see nothing rendered [here](http://networkx-metis.readthedocs.org/en/latest/reference/generated/nxmetis.enums.MetisPType.html#nxmetis.enums.MetisPType) in the one Attributes table.

**Comment by ysitu** [comment]
I want to see if fixing #52 also fixes this.

**Comment by OrkoHunter** [comment]
The Attributes table is still without any content.

**Comment by ysitu** [comment]
Hmm... I triggered a doc rebuild, and now docstrings of enum values show up in the tables.

**Comment by OrkoHunter** [comment]
That looks great!

**Comment by ysitu** [comment]
After that I rebuilt several times. Sometimes it worked, sometimes it didn't. Still not sure why that change from build to build.

**Comment by OrkoHunter** [comment]
Okay, so can we make new branch from here on and refer 'latest' on readthedocs to that branch? This will  prevent from re-building several times.

**Comment by ysitu** [comment]
Not sure what you mean. I manually triggered the rebuild on the readthedocs site.

**Comment by OrkoHunter** [comment]
Because the documentation sometimes work and sometimes didn't, I suggest to create a new branch in the repository like `stable` which would be in the sense of "stable-documentation". And on [readthedocs](https://readthedocs.org/dashboard/networkx-metis/versions/), we make the 'latest' version inactive and the 'stable' version active.

This is just a simple hack to stop continuous builds over the active version on readthedocs which might disturb the documentation.

**Pull request closed without merging**
