### PR TITLE
Add tests inside installed package

### PR DESCRIPTION
**Pull request by OrkoHunter**
We need this at first place for the tests to run inside `site-packages`.

### CODE REVIEW

**Comment by chebee7i** [comment]
Why not just add an `__init__.py` file in the `tests` subdirectory?  How you have it currently is different from how we do it in networkx. Not saying that they necessary need to be the the same though...

**Comment by OrkoHunter** [comment]
Having `package_data` for including tests (as it is in NetworkX) seems okay to me.

**Comment by chebee7i** [comment]
It seems like putting them in `package_data` contradicts the fact that we have `__init__.py` files in the test directories. E.g., in networkx (and maybe here), we should just add the test directories to `packages`. This would simplify `package_data` quite a bit.

**Comment by OrkoHunter** [comment]
Perfect. Added it into packages.

**Comment by chebee7i** [comment]
I think this requires that you have an empty `__init__.py` in the `tests` subdirectory.

**Comment by chebee7i** [comment]
Opps I'm blind.

**Comment by OrkoHunter** [comment]
Thanks! I'll rebase and run the travis script.

**Pull request merged**
