### PR TITLE
Identation fix in types.py

### PR DESCRIPTION
**Pull request by OrkoHunter**
Wow, theses little things I didn't notice. Thanks Travis.

### CODE REVIEW

**Comment by chebee7i** [comment]
Is this going into the right repository? Looks like it is going into networkx:master.

**Comment by OrkoHunter** [comment]
Well this PR is #17 of `networkx-metis` seeing from URL. And `networkx` doesn't even have any `networkx.addons.metis.types`. I think the scheme of that is <username>:<branch> and <organization>:<branch>. Nothing to do with repository in both case.

**Comment by chebee7i** [comment]
Strange that I never noticed it before...and it indeed the same on other PRs.   But it still seems out.  The syntax is:   `repositoryname:branchname`. So when it says:

	OrkoHunter  wants to merge 1 commit into networkx:master from OrkoHunter:types_fix

the definitely seems "off".

**Comment by chebee7i** [comment]
In the repository settings, is there some way to specify this and it is just specified wrong?

**Comment by chebee7i** [comment]
Looks like it is ubiquitous.  The format is actually `username:branchname`. So like you said, the repository name is not part of it.

**Comment by OrkoHunter** [comment]
Maybe it's a new change? That's why we never noticed it earlier.

**Pull request merged**
